name: Vue CI

on: push

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@master
    - name: Install, build, test
      run: |
        npm install
        npm run build
        npm test
      env:
        CI: true

  checkCodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@master
    - name: Install and check codestyle
      run: |
        npm install
        npm run codestyle
      env:
        CI: true
