name: Vue CI

on: push

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@master
    - name: Install
      run: npm --prefix /home/runner/work/map-projects-teamDoshirak/map-projects-teamDoshirak/quizgame install -d
    - name: build
      run: npm run build
    - name: test
      run: npm test
      env:
        CI: true

  checkCodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@master
    - name: Install and check codestyle
      run: |
        npm install
        npm run codestyle
      env:
        CI: true
