name: Vue CI

on: push

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@master
    - name: install
      run: npm --prefix /home/runner/work/map-projects-teamDoshirak/map-projects-teamDoshirak/quizgame install -d
    - name: build
      run: npm --prefix /home/runner/work/map-projects-teamDoshirak/map-projects-teamDoshirak/quizgame run build
    - name: test
      run: npm --prefix /home/runner/work/map-projects-teamDoshirak/map-projects-teamDoshirak/quizgame test --outputFile=results.html --colors
    - name: lsroot
      run: ls
    - name: lsquizgames
      run: ls /home/runner/work/map-projects-teamDoshirak/map-projects-teamDoshirak/quizgame
    - name: lsdist
      run: ls /home/runner/work/map-projects-teamDoshirak/map-projects-teamDoshirak/quizgame/dist
    - name: lspublic
      run: ls /home/runner/work/map-projects-teamDoshirak/map-projects-teamDoshirak/quizgame/public
    - name: lstests
      run: ls /home/runner/work/map-projects-teamDoshirak/map-projects-teamDoshirak/quizgame/tests
      env:
        CI: true
