name: Vue CI

on: push

jobs:
  buildAndTest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@master
    - name: Install
      run: npm install
    - name: Init, update, build, test
      run: |
        npm update
        npm run build
        npm test
      env:
        CI: true

  checkCodestyle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@master
    - name: Install and check codestyle
      run: |
        npm install
        npm run codestyle
      env:
        CI: true
